getOrdersByMaker
1inch/fusion-sdk pull request #4
Opened 2023-01-31 14:09 UTC by frolovdev

2023-01-31 14:15 UTC, frolovdev commented on src/api/orders/orders.request.ts
> +    buildQueryParams(): OrdersByMakerQueryParams {
📓 I don't know is it a good idea to be more precisely in naming here

2023-02-01 11:50 UTC, krboktv requested changes

2023-02-01 13:39 UTC, frolovdev commented on src/api/orders/orders.request.ts
> +    buildQueryParams(): OrdersByMakerQueryParams {
done 
src/api/pagination.ts
src/api/pagination.spec.ts

2023-02-03 10:59 UTC, krboktv requested changes

2023-02-03 10:59 UTC, krboktv commented on src/api/orders/types.ts
> +}
This type can be moved nearby pagination types. And pagination you can wrap in the folder with `types.ts` file

2023-02-04 09:16 UTC, krboktv approved these changes

2023-02-04 09:27 UTC, merged